name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "*/10 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not seen any activity in 90 days. If the issue is still relevant, please comment on it or the issue will be automatically closed in 15 days. This way, the issue tracker can be kept clean. Thank you!'
        stale-issue-label: 'stale'
        days-before-stale: 90
        days-before-close: 15
        exempt-issue-labels: 'priority, never-stale' 
